title: "F2R Articles"
description: "All articles wrote by F2R: PHP, methodology, web, architecture, development, programming, and so."
author: "Frederic Bouchery"
url: https://f2r.github.io
baseurl: /
highlighter: rouge
kramdown:
  smart_quotes:               apos,apos,quot,quot
  typographic_symbols:        {hellip: ...}

remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

show_downloads: false

collections:
  fr:
    output: true
  en:
    output: true

feed:
  collections:
    - fr
    - en

